=== Kenshins/BooliCPP/areas.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://example.com/example.json",
  "type": "object",
  "properties": {
    "totalCount": {
      "$id": "/properties/totalCount",
      "type": "integer",
      "title": "The Totalcount Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": 0,
      "examples": [
        5
      ]
    },
    "count": {
      "$id": "/properties/count",
      "type": "integer",
      "title": "The Count Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": 0,
      "examples": [
        5
      ]
    },
    "areas": {
      "$id": "/properties/areas",
      "type": "array",
      "items": {
        "$id": "/properties/areas/items",
        "type": "object",
        "properties": {
          "booliId": {
            "$id": "/properties/areas/items/properties/booliId",
            "type": "integer",
            "title": "The Booliid Schema.",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
              76
            ]
          },
          "name": {
            "$id": "/properties/areas/items/properties/name",
            "type": "string",
            "title": "The Name Schema.",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
              "Nacka"
            ]
          },
          "types": {
            "$id": "/properties/areas/items/properties/types",
            "type": "array",
            "items": {
              "$id": "/properties/areas/items/properties/types/items",
              "type": "string",
              "title": "The 0 Schema.",
              "description": "An explanation about the purpose of this instance.",
              "default": "",
              "examples": [
                "Kommun"
              ]
            }
          },
          "parentBooliId": {
            "$id": "/properties/areas/items/properties/parentBooliId",
            "type": "integer",
            "title": "The Parentbooliid Schema.",
            "description": "An explanation about the purpose of this instance.",
            "default": 0,
            "examples": [
              2
            ]
          },
          "parentName": {
            "$id": "/properties/areas/items/properties/parentName",
            "type": "string",
            "title": "The Parentname Schema.",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
              "Stockholms län"
            ]
          },
          "parentTypes": {
            "$id": "/properties/areas/items/properties/parentTypes",
            "type": "array",
            "items": {
              "$id": "/properties/areas/items/properties/parentTypes/items",
              "type": "string",
              "title": "The 0 Schema.",
              "description": "An explanation about the purpose of this instance.",
              "default": "",
              "examples": [
                "Län"
              ]
            }
          },
          "fullName": {
            "$id": "/properties/areas/items/properties/fullName",
            "type": "string",
            "title": "The Fullname Schema.",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
              "Nacka, Stockholms län"
            ]
          },
          "urlFriendlyName": {
            "$id": "/properties/areas/items/properties/urlFriendlyName",
            "type": "string",
            "title": "The Urlfriendlyname Schema.",
            "description": "An explanation about the purpose of this instance.",
            "default": "",
            "examples": [
              "nacka"
            ]
          }
        }
      }
    },
    "searchParams": {
      "$id": "/properties/searchParams",
      "type": "object",
      "properties": {
        "q": {
          "$id": "/properties/searchParams/properties/q",
          "type": "string",
          "title": "The Q Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "nacka"
          ]
        },
        "listings": {
          "$id": "/properties/searchParams/properties/listings",
          "type": "integer",
          "title": "The Listings Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            1
          ]
        },
        "transactions": {
          "$id": "/properties/searchParams/properties/transactions",
          "type": "integer",
          "title": "The Transactions Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            0
          ]
        }
      }
    },
    "limit": {
      "$id": "/properties/limit",
      "type": "integer",
      "title": "The Limit Schema.",
      "description": "An explanation about the purpose of this instance.",
      "default": 0,
      "examples": [
        5
      ]
    }
  }
}

=== Kenshins/BooliCPP/areastestdata.json
{"totalCount":9,"count":9,"areas":[{"booliId":76,"name":"Nacka","types":["Kommun"],"parentBooliId":2,"parentName":"Stockholms l\u00e4n","parentTypes":["L\u00e4n"],"fullName":"Nacka, Stockholms l\u00e4n","urlFriendlyName":"nacka"},{"booliId":930508,"name":"Nacka Strand","types":["undefined"],"parentBooliId":76,"parentName":"Nacka","parentTypes":["Kommun"],"fullName":"Nacka Strand, Nacka","urlFriendlyName":"nacka+strand"},{"booliId":24617,"name":"Nacka Forum","types":["undefined"],"parentBooliId":76,"parentName":"Nacka","parentTypes":["Kommun"],"fullName":"Nacka Forum, Nacka","urlFriendlyName":"nacka+forum"},{"booliId":940036,"name":"Finntorp Nacka","types":["undefined"],"parentBooliId":76,"parentName":"Nacka","parentTypes":["Kommun"],"fullName":"Finntorp Nacka, Nacka","urlFriendlyName":"finntorp+nacka"},{"booliId":965203,"name":"Ektorp Nacka","types":["undefined"],"parentBooliId":76,"parentName":"Nacka","parentTypes":["Kommun"],"fullName":"Ektorp Nacka, Nacka","urlFriendlyName":"ektorp+nacka"},{"booliId":930392,"name":"Nacka Saltsj\u00f6qvarn","types":["undefined"],"parentBooliId":1,"parentName":"Stockholm","parentTypes":["Kommun"],"fullName":"Nacka Saltsj\u00f6qvarn, Stockholm","urlFriendlyName":"nacka+saltsjoqvarn"},{"booliId":937057,"name":"Jarlaberg-Nacka","types":["undefined"],"parentBooliId":76,"parentName":"Nacka","parentTypes":["Kommun"],"fullName":"Jarlaberg-Nacka, Nacka","urlFriendlyName":"jarlaberg-nacka"},{"booliId":966438,"name":"Henriksdalsberget Nacka","types":["undefined"],"parentBooliId":76,"parentName":"Nacka","parentTypes":["Kommun"],"fullName":"Henriksdalsberget Nacka, Nacka","urlFriendlyName":"henriksdalsberget+nacka"},{"booliId":106799,"name":"Nackagatan","types":["Street"],"parentBooliId":1,"parentName":"Stockholm","parentTypes":["Kommun"],"fullName":"Nackagatan, Stockholm","urlFriendlyName":"nackagatan"}],"searchParams":{"q":"Nacka","listings":1,"transactions":0},"limit":30}
