=== Kenshins/BooliCPP/sold.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://example.com/example.json",
  "type": "object",
  "properties": {
    "totalCount": {
      "$id": "/properties/totalCount",
      "type": "integer",
      "default": 0,
      "examples": [
        6530
      ]
    },
    "count": {
      "$id": "/properties/count",
      "type": "integer",
      "default": 0,
      "examples": [
        5
      ]
    },
    "sold": {
      "$id": "/properties/sold",
      "type": "array",
      "items": {
        "$id": "/properties/sold/items",
        "type": "object",
        "properties": {
          "location": {
            "$id": "/properties/sold/items/properties/location",
            "type": "object",
            "properties": {
              "address": {
                "$id": "/properties/sold/items/properties/location/properties/address",
                "type": "object",
                "properties": {
                  "streetAddress": {
                    "$id": "/properties/sold/items/properties/location/properties/address/properties/streetAddress",
                    "type": "string",
                    "default": "",
                    "examples": [
                      "Fabrikörvägen 10D"
                    ]
                  }
                }
              },
              "position": {
                "$id": "/properties/sold/items/properties/location/properties/position",
                "type": "object",
                "properties": {
                  "latitude": {
                    "$id": "/properties/sold/items/properties/location/properties/position/properties/latitude",
                    "type": "number",
                    "default": 0,
                    "examples": [
                      59.31668472290039
                    ]
                  },
                  "longitude": {
                    "$id": "/properties/sold/items/properties/location/properties/position/properties/longitude",
                    "type": "number",
                    "default": 0,
                    "examples": [
                      18.1539363861084
                    ]
                  }
                }
              },
              "namedAreas": {
                "$id": "/properties/sold/items/properties/location/properties/namedAreas",
                "type": "array",
                "items": {
                  "$id": "/properties/sold/items/properties/location/properties/namedAreas/items",
                  "type": "string",
                  "default": "",
                  "examples": [
                    "Nacka Strand"
                  ]
                }
              },
              "region": {
                "$id": "/properties/sold/items/properties/location/properties/region",
                "type": "object",
                "properties": {
                  "municipalityName": {
                    "$id": "/properties/sold/items/properties/location/properties/region/properties/municipalityName",
                    "type": "string",
                    "default": "",
                    "examples": [
                      "Nacka"
                    ]
                  },
                  "countyName": {
                    "$id": "/properties/sold/items/properties/location/properties/region/properties/countyName",
                    "type": "string",
                    "default": "",
                    "examples": [
                      "Stockholms län"
                    ]
                  }
                }
              },
              "distance": {
                "$id": "/properties/sold/items/properties/location/properties/distance",
                "type": "object",
                "properties": {
                  "ocean": {
                    "$id": "/properties/sold/items/properties/location/properties/distance/properties/ocean",
                    "type": "number",
                    "default": 0,
                    "examples": [
                      108
                    ]
                  }
                }
              }
            }
          },
          "listPrice": {
            "$id": "/properties/sold/items/properties/listPrice",
            "type": "number",
            "default": 0,
            "examples": [
              5495000
            ]
          },
          "rent": {
            "$id": "/properties/sold/items/properties/rent",
            "type": "number",
            "default": 0,
            "examples": [
              5853
            ]
          },
          "livingArea": {
            "$id": "/properties/sold/items/properties/livingArea",
            "type": "number",
            "default": 0,
            "examples": [
              108
            ]
          },
          "additionalArea": {
            "$id": "/properties/sold/items/properties/additionalArea",
            "type": "number",
            "default": 0,
            "examples": [
              2
            ]
          },
          "plotArea": {
            "$id": "/properties/sold/items/properties/plotArea",
            "type": "integer",
            "default": 0,
            "examples": [
              0
            ]
          },
          "source": {
            "$id": "/properties/sold/items/properties/source",
            "type": "object",
            "properties": {
              "name": {
                "$id": "/properties/sold/items/properties/source/properties/name",
                "type": "string",
                "default": "",
                "examples": [
                  "Notar"
                ]
              },
              "id": {
                "$id": "/properties/sold/items/properties/source/properties/id",
                "type": "integer",
                "default": 0,
                "examples": [
                  1566
                ]
              },
              "type": {
                "$id": "/properties/sold/items/properties/source/properties/type",
                "type": "string",
                "default": "",
                "examples": [
                  "Broker"
                ]
              },
              "url": {
                "$id": "/properties/sold/items/properties/source/properties/url",
                "type": "string",
                "default": "",
                "examples": [
                  "http://www.notar.se/"
                ]
              }
            }
          },
          "rooms": {
            "$id": "/properties/sold/items/properties/rooms",
            "type": "number",
            "default": 0,
            "examples": [
              3
            ]
          },
          "published": {
            "$id": "/properties/sold/items/properties/published",
            "type": "string",
            "default": "",
            "examples": [
              "2017-12-04 18:12:56"
            ]
          },
          "objectType": {
            "$id": "/properties/sold/items/properties/objectType",
            "type": "string",
            "default": "",
            "examples": [
              "Lägenhet"
            ]
          },
          "booliId": {
            "$id": "/properties/sold/items/properties/booliId",
            "type": "integer",
            "default": 0,
            "examples": [
              3053907
            ]
          },
          "soldDate": {
            "$id": "/properties/sold/items/properties/soldDate",
            "type": "string",
            "default": "",
            "examples": [
              "2017-12-27"
            ]
          },
          "soldPrice": {
            "$id": "/properties/sold/items/properties/soldPrice",
            "type": "number",
            "default": 0,
            "examples": [
              5495000
            ]
          },
          "soldPriceSource": {
            "$id": "/properties/sold/items/properties/soldPriceSource",
            "type": "string",
            "default": "",
            "examples": [
              "bid"
            ]
          },
          "url": {
            "$id": "/properties/sold/items/properties/url",
            "type": "string",
            "default": "",
            "examples": [
              "https://www.booli.se/annons/3053907"
            ]
          }
        }
      }
    },
    "limit": {
      "$id": "/properties/limit",
      "type": "integer",
      "default": 0,
      "examples": [
        5
      ]
    },
    "offset": {
      "$id": "/properties/offset",
      "type": "integer",
      "default": 0,
      "examples": [
        0
      ]
    },
    "searchParams": {
      "$id": "/properties/searchParams",
      "type": "object",
      "properties": {
        "areaId": {
          "$id": "/properties/searchParams/properties/areaId",
          "type": "integer",
          "default": 0,
          "examples": [
            76
          ]
        }
      }
    }
  }
}

=== Kenshins/BooliCPP/soldtestdata.json
{"totalCount":6730,"count":30,"sold":[{"location":{"address":{"streetAddress":"Sickla All\u00e9 13"},"position":{"latitude":59.30233763,"longitude":18.1161066},"namedAreas":["Sickla All\u00e9"],"region":{"municipalityName":"Nacka","countyName":"Stockholms l\u00e4n"},"distance":{"ocean":815}},"listPrice":2495000,"rent":2246,"floor":6,"livingArea":38,"source":{"name":"Svenska M\u00e4klarhuset","id":58,"type":"Broker","url":"http:\/\/www.svenskamaklarhuset.se\/"},"rooms":1.5,"published":"2017-12-29 02:28:40","constructionYear":1959,"objectType":"L\u00e4genhet","booliId":3063170,"soldDate":"2018-01-27","soldPrice":2400000,"soldPriceSource":"bid","url":"https:\/\/www.booli.se\/annons\/3063170"},{"location":{"address":{"streetAddress":"Tranv\u00e4gen 11"},"position":{"latitude":59.31100894,"longitude":18.21106835},"namedAreas":["Salt\u00e4ngen"],"region":{"municipalityName":"Nacka","countyName":"Stockholms l\u00e4n"},"distance":{"ocean":363}},"listPrice":2750000,"rent":3486,"floor":2,"livingArea":69,"source":{"name":"L\u00e4nsf\u00f6rs\u00e4kringar Fastighetsf\u00f6rmedling","id":64,"type":"Broker","url":"http:\/\/www.lansfast.se\/"},"rooms":2,"published":"2018-01-10 20:32:39","constructionYear":1990,"objectType":"L\u00e4genhet","booliId":3068079,"soldDate":"2018-01-27","soldPrice":2930000,"soldPriceSource":"bid","url":"https:\/\/www.booli.se\/annons\/3068079"},{"location":{"address":{"streetAddress":"Mj\u00f6lnarv\u00e4gen 22"},"position":{"latitude":59.31778173,"longitude":18.13989758},"namedAreas":["Kvarnholmen"],"region":{"municipalityName":"Nacka","countyName":"Stockholms l\u00e4n"},"distance":{"ocean":39}},"listPrice":2975000,"rent":2760,"floor":4,"livingArea":54.5,"source":{"name":"Svensk Fastighetsf\u00f6rmedling","id":713,"type":"Broker","url":"http:\/\/www.svenskfast.se\/"},"rooms":2,"published":"2017-12-21 16:18:23","objectType":"L\u00e4genhet","booliId":3060718,"soldDate":"2018-01-27","soldPrice":3175000,"soldPriceSource":"bid","url":"https:\/\/www.booli.se\/annons\/3060718"},{"location":{"address":{"streetAddress":"Ut\u00f6v\u00e4gen 15","city":"Boo"},"position":{"latitude":59.32394565,"longitude":18.25308681},"namedAreas":["V\u00e4stra Orminge"],"region":{"municipalityName":"Nacka","countyName":"Stockholms l\u00e4n"},"distance":{"ocean":1670}},"listPrice":2495000,"rent":4213,"floor":1,"livingArea":70,"source":{"name":"Svenska M\u00e4klarhuset","id":58,"type":"Broker","url":"http:\/\/www.svenskamaklarhuset.se\/"},"rooms":3,"published":"2018-01-12 02:06:59","constructionYear":1967,"objectType":"L\u00e4genhet","booliId":3069047,"soldDate":"2018-01-27","soldPrice":2580000,"soldPriceSource":"bid","url":"https:\/\/www.booli.se\/annons\/3069047"},{"location":{"address":{"streetAddress":"R\u00f6dhakev\u00e4gen 2","city":"Boo"},"position":{"latitude":59.30568688,"longitude":18.24954636},"namedAreas":["L\u00e4nnersta"],"region":{"municipalityName":"Nacka","countyName":"Stockholms l\u00e4n"},"distance":{"ocean":619}},"listPrice":8395000,"livingArea":151,"plotArea":2300,"source":{"name":"Svenska M\u00e4klarhuset","id":58,"type":"Broker","url":"http:\/\/www.svenskamaklarhuset.se\/"},"rooms":6,"published":"2018-01-09 20:13:43","constructionYear":2004,"objectType":"Villa","booliId":3030713,"soldDate":"2018-01-26","soldPrice":8000000,"soldPriceSource":"bid","url":"https:\/\/www.booli.se\/annons\/3030713"},{"location":{"address":{"streetAddress":"Ormingeringen 70","city":"Boo"},"position":{"latitude":59.3327,"longitude":18.2516},"namedAreas":["Saltsj\u00f6-Boo"],"region":{"municipalityName":"Nacka","countyName":"Stockholms l\u00e4n"},"distance":{"ocean":1555}},"listPrice":1495000,"rent":2523,"floor":1,"livingArea":37,"source":{"name":"Svensk Fastighetsf\u00f6rmedling","id":713,"type":"Broker","url":"http:\/\/www.svenskfast.se\/"},"rooms":1.5,"published":"2018-01-09 15:34:11","constructionYear":1970,"objectType":"L\u00e4genhet","booliId":3067368,"soldDate":"2018-01-26","soldPrice":1750000,"soldPriceSource":"bid","url":"https:\/\/www.booli.se\/annons\/3067368"},{"location":{"address":{"streetAddress":"Alphyddev\u00e4gen 33"},"position":{"latitude":59.30741899,"longitude":18.12275614},"namedAreas":["Alphyddan"],"region":{"municipalityName":"Nacka","countyName":"Stockholms l\u00e4n"},"distance":{"ocean":237}},"listPrice":2250000,"rent":2491,"floor":6,"livingArea":38.5,"additionalArea":0,"source":{"name":"Bjurfors","id":1561,"type":"Broker","url":"http:\/\/www.bjurfors.se\/"},"rooms":1,"published":"2018-01-10 15:23:53","constructionYear":1962,"objectType":"L\u00e4genhet","booliId":3067827,"soldDate":"2018-01-26","soldPrice":2500000,"apartmentNumber":"1702","soldPriceSource":"bid","url":"https:\/\/www.booli.se\/annons\/3067827"},{"location":{"address":{"streetAddress":"Orn\u00f6v\u00e4gen 18","city":"Boo"},"position":{"latitude":59.33081989,"longitude":18.25889111},"namedAreas":["V\u00e4stra Orminge"],"region":{"municipalityName":"Nacka","countyName":"Stockholms l\u00e4n"},"distance":{"ocean":1775}},"listPrice":1895000,"rent":4639,"floor":1,"livingArea":81,"source":{"name":"Svenska M\u00e4klarhuset","id":58,"type":"Broker","url":"http:\/\/www.svenskamaklarhuset.se\/"},"rooms":3,"published":"2018-01-12 02:27:35","constructionYear":1970,"objectType":"L\u00e4genhet","booliId":3069049,"soldDate":"2018-01-26","soldPrice":1950000,"soldPriceSource":"bid","url":"https:\/\/www.booli.se\/annons\/3069049"},{"location":{"address":{"streetAddress":"Orn\u00f6v\u00e4gen 10","city":"Boo"},"position":{"latitude":59.33107162,"longitude":18.26025367},"namedAreas":["Orminge"],"region":{"municipalityName":"Nacka","countyName":"Stockholms l\u00e4n"},"distance":{"ocean":1740}},"listPrice":1595000,"rent":3616,"floor":1,"livingArea":61,"additionalArea":0,"source":{"name":"Erik Olsson Fastighetsf\u00f6rmedling","id":1564,"type":"Broker","url":"http:\/\/www.erikolsson.se\/"},"rooms":2,"published":"2018-01-12 16:19:23","constructionYear":1970,"objectType":"L\u00e4genhet","booliId":3069594,"soldDate":"2018-01-26","soldPrice":2000000,"soldPriceSource":"bid","url":"https:\/\/www.booli.se\/annons\/3069594"},{"location":{"address":{"streetAddress":"Diligensv\u00e4gen 38"},"position":{"latitude":59.31585206,"longitude":18.17267513},"namedAreas":["Jarlaberg"],"region":{"municipalityName":"Nacka","countyName":"Stockholms l\u00e4n"},"distance":{"ocean":618}},"listPrice":1795000,"rent":4257,"floor":1,"livingArea":63,"plotArea":0,"source":{"name":"Notar","id":1566,"type":"Broker","url":"http:\/\/www.notar.se\/"},"rooms":2,"published":"2018-01-11 14:45:06","constructionYear":1988,"objectType":"L\u00e4genhet","booliId":3068590,"soldDate":"2018-01-25","soldPrice":2100000,"soldPriceSource":"bid","url":"https:\/\/www.booli.se\/annons\/3068590"},{"location":{"address":{"streetAddress":"Siloplatsen 6"},"position":{"latitude":59.3171103,"longitude":18.1407299},"namedAreas":["Kvarnholmen"],"region":{"municipalityName":"Nacka","countyName":"Stockholms l\u00e4n"},"distance":{"ocean":105}},"listPrice":3200000,"rent":2970,"floor":13,"livingArea":54,"plotArea":0,"source":{"name":"Notar","id":1566,"type":"Broker","url":"http:\/\/www.notar.se\/"},"rooms":2,"published":"2018-01-09 20:02:20","constructionYear":2014,"objectType":"L\u00e4genhet","booliId":3067470,"soldDate":"2018-01-25","soldPrice":3100000,"soldPriceSource":"bid","url":"https:\/\/www.booli.se\/annons\/3067470"},{"location":{"address":{"streetAddress":"Vinterv\u00e4gen 1A","city":"Boo"},"position":{"latitude":59.31867409,"longitude":18.24228287},"namedAreas":["Bj\u00f6rkn\u00e4s"],"region":{"municipalityName":"Nacka","countyName":"Stockholms l\u00e4n"},"distance":{"ocean":992}},"listPrice":2975000,"rent":4388,"floor":3,"livingArea":74,"additionalArea":0,"source":{"name":"Bjurfors","id":1561,"type":"Broker","url":"http:\/\/www.bjurfors.se\/"},"rooms":3,"published":"2017-12-27 07:37:43","constructionYear":2007,"objectType":"L\u00e4genhet","booliId":3058586,"soldDate":"2018-01-23","soldPrice":3100000,"soldPriceSource":"admin","url":"https:\/\/www.booli.se\/annons\/3058586"},{"location":{"address":{"streetAddress":"Tallidsv\u00e4gen 9B"},"position":{"latitude":59.30935287,"longitude":18.13844299},"namedAreas":["Finntorp"],"region":{"municipalityName":"Nacka","countyName":"Stockholms l\u00e4n"},"distance":{"ocean":303}},"listPrice":1595000,"rent":2318,"floor":3,"livingArea":28,"plotArea":1788,"source":{"name":"M\u00e4klarhuset","id":204,"type":"Broker","url":"http:\/\/www.maklarhuset.se\/"},"rooms":1,"published":"2017-09-15 20:01:16","constructionYear":1952,"objectType":"L\u00e4genhet","booliId":2411769,"soldDate":"2018-01-23","soldPrice":1700000,"soldPriceSource":"admin","url":"https:\/\/www.booli.se\/annons\/2411769"},{"location":{"address":{"streetAddress":"\u00d6stra Finnbodav\u00e4gen 11C"},"position":{"latitude":59.31465661,"longitude":18.11316575},"namedAreas":["Saltsj\u00f6qvarn"],"region":{"municipalityName":"Nacka","countyName":"Stockholms l\u00e4n"},"distance":{"ocean":109}},"listPrice":2350000,"rent":3851,"floor":1,"livingArea":50.5,"additionalArea":0,"source":{"name":"Bjurfors","id":1561,"type":"Broker","url":"http:\/\/www.bjurfors.se\/"},"rooms":2,"published":"2017-12-28 22:59:59","constructionYear":2006,"objectType":"L\u00e4genhet","booliId":3063146,"soldDate":"2018-01-25","soldPrice":2510000,"apartmentNumber":"1002","soldPriceSource":"bid","url":"https:\/\/www.booli.se\/annons\/3063146"},{"location":{"address":{"streetAddress":"Fabrik\u00f6rv\u00e4gen 10A"},"position":{"latitude":59.31668998,"longitude":18.15627791},"namedAreas":["Nacka Strand"],"region":{"municipalityName":"Nacka","countyName":"Stockholms l\u00e4n"},"distance":{"ocean":170}},"listPrice":5975000,"rent":5378,"floor":2,"livingArea":110,"source":{"name":"ERA","id":1562,"type":"Broker","url":"http:\/\/www.erasweden.com\/"},"isNewConstruction":1,"rooms":4,"published":"2017-12-07 18:40:01","constructionYear":2017,"objectType":"L\u00e4genhet","booliId":3055579,"soldDate":"2018-01-25","soldPrice":5975000,"soldPriceSource":"bid","url":"https:\/\/w
